### DISCUSSION TITLE
Project HÆLTH Blog #8

### DISCUSSION THREAD

**Discussion by j1tbk** [ldcdorn/haelth#69] [General]
# Project HÆLTH 🌱

This week we set up a  CI/CD-Pipeline to automate tasks such as testing, building, and deployment, reducing manual effort and human error. 

# Pipeline

```

name: Generated APK AAB (Upload - Create Artifact To Github Action)

env:
  # The name of the main module repository
  main_project_module: Haelth

  # The name of the Play Store
  playstore_name: NA

on:

  push:
    branches:
      - 'release/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set Current Date As Env Variable
      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      # Set Repository Name As Env Variable
      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'gradle'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      # Run Tests Build
      - name: Run gradle tests
        run: ./gradlew test

      # Run Build Project
      - name: Build gradle project
        run: ./gradlew build

      # Create APK Debug
      - name: Build apk debug project (APK) - ${{ env.main_project_module }} module
        run: ./gradlew assembleDebug

      # Create APK Release
      - name: Build apk release project (APK) - ${{ env.main_project_module }} module
        run: ./gradlew assemble

      # Create Bundle AAB Release
      # Noted for main module build [main_project_module]:bundleRelease
      - name: Build app bundle release (AAB) - ${{ env.main_project_module }} module
        run: ./gradlew ${{ env.main_project_module }}:bundleRelease

      # Upload Artifact Build
      # Noted For Output [main_project_module]/build/outputs/apk/debug/
      - name: Upload APK Debug - ${{ env.repository_name }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.date_today }} - ${{ env.playstore_name }} - ${{ env.repository_name }} - APK(s) debug generated
          path: ${{ env.main_project_module }}/build/outputs/apk/debug/

      # Noted For Output [main_project_module]/build/outputs/apk/release/
      - name: Upload APK Release - ${{ env.repository_name }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.date_today }} - ${{ env.playstore_name }} - ${{ env.repository_name }} - APK(s) release generated
          path: ${{ env.main_project_module }}/build/outputs/apk/release/

      # Noted For Output [main_project_module]/build/outputs/bundle/release/
      - name: Upload AAB (App Bundle) Release - ${{ env.repository_name }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.date_today }} - ${{ env.playstore_name }} - ${{ env.repository_name }} - App bundle(s) AAB release generated
          path: ${{ env.main_project_module }}/build/outputs/bundle/release/

```

# Workflow Details

## Trigger Conditions

1. Push to Branches Matching release/**:
- The pipeline triggers automatically when changes are pushed to branches with names starting with release/.
- Manual Trigger:
  It can also be started manually via the "Run workflow" button in the Actions tab.
## Environment Variables
- main_project_module: The name of the main project module (Haelth).
- playstore_name: Name of the Play Store (not actively used here, set to NA).
## Job: build
  - Runs on ubuntu-latest.

# Steps
1. Checkout Code:
Uses the actions/checkout@v4 action to fetch the code from the repository.

2. Set Current Date as an Environment Variable:

- Retrieves the current date in YYYY-MM-DD format and stores it in the GITHUB_ENV file, making it accessible to subsequent steps.

3. Set Repository Name as an Environment Variable:

- Extracts the repository name from the GitHub context and stores it as an environment variable.

4. Set Up JDK:

- Installs Java 17 using the Zulu distribution and caches Gradle dependencies to speed up builds.

5. Change Wrapper Permissions:

- Grants execute permissions to the Gradle wrapper script (gradlew).

6. Run Gradle Tests:

- Executes the project's tests using ./gradlew test.

7. Build the Project:

- Runs ./gradlew build to compile and package the project.

8. Build APK (Debug):

- Generates the debug APK using ./gradlew assembleDebug.

9. Build APK (Release):

- Generates the release APK using ./gradlew assemble.

10. Build App Bundle (AAB) Release:

- Builds the release AAB (Android App Bundle) for the specified module using ./gradlew Haelth:bundleRelease.

11. Upload Artifacts:

- Uploads the generated files as artifacts to GitHub for download.

- Debug APK:

-- Path: Haelth/build/outputs/apk/debug/
-- Artifact Name: Includes the current date, Play Store name, and repository name.
- Release APK:

-- Path: Haelth/build/outputs/apk/release/
-- Artifact Name: Similar to debug APK but indicates "release".
- Release AAB:

-- Path: Haelth/build/outputs/bundle/release/
-- Artifact Name: Similar to APKs but indicates "AAB release".
